export default {
    THEME_CHANGE: "THEME_CHANGE",
    THEME_INIT: "THEME_INIT",
    POPULAR_REFEESHING: 'POPULAR_REFEESHING',
    LOAD_POPULAR_FAIL: 'LOAD_POPULAR_FAIL',
    LOAD_POPULAR_SUCCESS: 'LOAD_POPULAR_SUCCESS',
    POPULAR_LOAD_MORE_SUCCESS:"POPULAR_LOAD_MORE_SUCCESS",
    POPULAR_LOAD_MORE_FAIL:"POPULAR_LOAD_MORE_FAIL",
}